---
title: "Class08"
author: "Emily Kimball"
date: "10/24/2019"
output: "Github_Document"
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

##K-means clustering
```{r}
# Generate some example data for clustering
tmp <- c(rnorm(30,-3), rnorm(30,3))
#cbind is binding the columns togther 
x <- cbind(x=tmp, y=rev(tmp))
plot(x)
```
Answering questions 
```{r}
K <- kmeans(x, centers= 2 , nstart = 20)
K
```#coloring the points 
```{r}
K$center
plot(x, col=K$cluster)
```

Finding the centers 
```{r}
points(K$centers, col = "blue", pch=15)
```
##Clustering 
the Hclust() function requires a distance matrix as input, you can get from dist() function 
```{r}
# First we need to calculate point (dis)similarity
# as the Euclidean distance between observations
dist_matrix <- dist(x)
# The hclust() function returns a hierarchical
# clustering model
hc <- hclust(d = dist_matrix)
# the print method is not so useful here
hc

```#making the chart 
```{r}
plot(hc)
#adds a line 
abline(h=6, col = "red")
#cuting the tree
 groups <- cutree(hc, h=6) # cut into k or h groups 
```
#Hands on section 
```{r}
# Step 1. Generate some example data for clustering
x <- rbind(
 matrix(rnorm(100, mean=0, sd = 0.3), ncol = 2), # c1
 matrix(rnorm(100, mean = 1, sd = 0.3), ncol = 2), # c2
 matrix(c(rnorm(50, mean = 1, sd = 0.3), # c3
 rnorm(50, mean = 0, sd = 0.3)), ncol = 2))
colnames(x) <- c("x", "y")
# Step 2. Plot the data without clustering
plot(x)
# Step 3. Generate colors for known clusters
# (just so we can compare to hclust results)
col <- as.factor( rep(c("c1","c2","c3"), each=50) )
plot(x, col=col)
```

```{r}
tree <- dist(x)
tree_plot <- hclust(d = tree)
plot(tree_plot)
abline(h = 2, col = "red")
cut_tree <- cutree(tree_plot, k = 3)
cut_tree
```
```{r}
table(cut_tree, col)
```
#PCA analysis 
```{r}
x <- read.csv("https://tinyurl.com/expression-CSV", row.names = 1)

head(x)
dim(x)

#PCA 
pca <- prcomp(t(x), scale=TRUE)
attributes(pca)
#lets do PCA it makes the 2-d plot 
plot(pca$x[,1], pca$x[,2],
     col=c("red", "red", "red", "red", "blue", "blue", "blue", "blue", "blue"))
pca.var<- pca$sdev^2
pca.var.per <- round(pca.var/sum(pca.var)*100, 1)
pca.var.per
```

#Doing the food PCA analysis
```{r}
read.csv("UK_foods (1).csv", row.names = 1)
pca <- prcomp(t(x))
summary(pca)

plot(pca$x[,1], pca$x[,2])
```
##Answering the questions 
```{r}
barplot(as.matrix(x), beside=T, col=rainbow(nrow(x)))
```
## trying PCA again 
```{r}
summary(fpca)
plot(fpca$x[,1], fpca$x[,2], xlab="PC1", ylab="PC2", xlim=c(-270,500))
text(fpca$x[,1], fpca$x[,2], colnames(x))
```



